name: Build Docker Image

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.1
      - name: Publish Docker Image to GitHub Packages
        uses: VaultVulp/gp-docker-action@1.1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: watame
          image-tag: production
          dockerfile: Dockerfile
          build-context: .
