name: Deploy to production

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.1
      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          git-ftp-args: --insecure
      - name: Send Power Action to Pterodactyl
        uses: fjogeleit/http-request-action@v1.3.1
        with:
          url: ${{ secrets.PANEL_URL }}
          method: 'POST'
          data: '{ "signal": "restart" }'
          bearerToken: ${{ secrets.PANEL_TOKEN }}
